development:
  adapter: postgresql
  encoding: unicode
  database: thanxup_dev
  pool: 5
  username: cnixon
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: thanxup_test
  pool: 5
  username: cnixon
  password:
